services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: node dist/index.js
    ports:
      - 80:8000
    working_dir: /app

  db:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_DB: 6502golf
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en-US"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - 6502golfdata:/var/lib/postgresql

volumes:
  6502golfdata: